_core:
  default_config_hash: 1TswGK46jyu77aIM7Z-0JVQs5bxHmo-gtgrvrQGMXxc
favicon:
  mimetype: image/jpeg
  path: 'public://imagess_3.jpg'
  use_default: true
features:
  comment_user_picture: true
  comment_user_verification: true
  favicon: true
  node_user_picture: false
logo:
  path: 'public://360_F_331316104_5Ggg8aZkuUHIZ1w7eGUS34o1zKbejUAf.jpg'
  use_default: false
third_party_settings:
  shortcut:
    module_link: true
mobile_menu_all_widths: 0
site_branding_bg_color: white
base_primary_color: '#8c3079'
