_core:
  default_config_hash: KZiV2LB312xgJBphfq5BTjmp16xiR5KM8InBJ-pff7Y
favicon:
  mimetype: image/jpeg
  path: 'public://imagess_1.jpg'
  url: ''
  use_default: true
features:
  comment_user_picture: true
  comment_user_verification: true
  favicon: true
  node_user_picture: false
logo:
  path: 'public://imagess_0.jpg'
  url: null
  use_default: true
